apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
<<<<<<< HEAD
      - name: php-app
        image: abhishekf5/ultimate-cicd:replaceImageTag
=======
      - name: spring-boot-app
        image: abhishekf5/ultimate-cicd:7
>>>>>>> 664fff9ca374b9b53cf78713b3395ed6ecbca62d
        ports:
        - containerPort: 8080
